import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import React from "react";
import {SpeedInsights} from "@vercel/speed-insights/next"
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import dynamic from "next/dynamic";

const PrelineScript = dynamic(() => import('./components/PrelineScript'))


const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Packagefy",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (

        <html lang="en">
        <SpeedInsights/>
        <body className={inter.className}>

        {children}
        <PrelineScript/>

        </body>
        </html>

    );
}
